version: "3"

volumes:
  mongo-data:

services:
  mongo:
    image: mongo:7.0.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
