volumes:
  mongo-data:

services:
  herda:
    image: herda:latest
    build:
      context: .
    ports:
      - "5001:5001"
    env_file: .docker.env

  mongo:
    image: mongo:7.0.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
